### ISSUE TITLE
Consume command

### ISSUE THREAD

**Issue by vongohren** [uport-project/uport-cli-client#6]
Hey im trying out this thing because it seems nice to have a better way for handling IDs that on the phone all the time.
So I thought I could hit consume with an URI, and then the login would continue on the app, because it is listening for confirmations. But I guess I was wrong.

What is the purpose of consume?

**Comment by zachferland** [comment]
@vongohren yeah then cli client allows you to manually handle what is considered a uPort ID on our platform, it will mostly be used for managing/creating app IDs in the future. The cli client has a similar interface to the mobile client (our mobile app). So just how the uport libraries create request URIs/Strings that the mobile app consumes (this will be more clear in the libs soon as well), you can pass the same type of request URIs/Strings through consume in the cli client. So the cli client is not tied to the mobile app in any way (no interaction between the two or their IDs), other than both being a uPort 'client'. 

Also the cli client is just a thin wrapper around uport-js-client, which is a javascript uPort client for creating/managing IDs. You may be interested in that as well.

**Comment by vongohren** [comment]
Ah ok, then what is the plan or how can I use one of the managed IDs from the cli, in some of the apps I develop? Or is this possible?

It's nice to have somewhere to handle and manage, but I just wonder how this can be reused into actually logging in somewhere. That is what I thought consume was for :)

Or can one import these IDs into the app some how? The reason for asking is to have multiple IDs to handle when developing, because ID's might have different roles

**Comment by vongohren** [comment]
Closing for cleanup
