### ISSUE TITLE
build fails due to dependancy on deprecated solidity-sh3

### ISSUE THREAD

**Issue by raininja** [uport-project/uport-cli-client#8]
doesn't build due to deprecation of solidity-sha3, which is in turn dependant on deprecated babel-preset-es2015@6.24.1

[https://travis-ci.org/raineorshine/solidity-sha3](url)

[https://github.com/raineorshine/solidity-sha3/pull/10](url)

```
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! solidity-sha3@0.4.1 postinstall: `npm run build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the solidity-sha3@0.4.1 postinstall script.

**Comment by kamescg** [comment]
@raininja Thanks for reporting this. Will look into as soon as possible.

**Comment by raininja** [comment]
I'm just going to fork the appropriate repos and use those to allow it to build.
